# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml


gcpreviews:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-go

controllerbuild:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-go

controllerteam:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/builder-go


docker-registry:
  enabled: true
  persistence:
    storageClass: "alicloud-disk-available"
    size: 20Gi

nexus:
  image:
    repository: gcr.azk8s.cn/jenkinsxio/nexus
  enabled: true
  persistence:
    storageClass: "alicloud-disk-available"
    size: 20Gi

chartmuseum:
  persistence:
    storageClass: "alicloud-disk-available"
    size: 20Gi

jenkins:
  Master:
    Image: "jenkinsxio/jenkinsx"
    ServiceType: LoadBalancer
  Agent:
    PodTemplates:
      Maven:
        Containers:
          Maven:
            Image: gcr.azk8s.cn/jenkinsxio/builder-maven:0.1.419
  Persistence:
    StorageClass: "alicloud-disk-available"
    Size: 40Gi

monocular:
  enabled: false


heapster:
  image:
    repository: gcr.azk8s.cn/google_containers/heapster
  resizer:
    image:
      repository: gcr.azk8s.cn/google_containers/addon-resizer

